# Generated by Django 6.0.1 on 2026-02-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=20)),
                ('Price', models.FloatField()),
                ('Manufracture_date', models.DateField()),
                ('Expiry_date', models.DateField()),
                ('Warrenty', models.CharField(max_length=10)),
            ],
        ),
    ]
